import { test, expect } from '@playwright/test';

test('caps scores and reminds users to back up without interrupting entry', async ({ page }) => {
  await page.goto('/');
  await page.getByLabel('Team names').fill('Aces\nSpinners\nLobsters\nDinkers');
  await page.getByRole('button', { name: 'Create tournament' }).click();
  const reminder = page.getByRole('complementary', { name: 'Backup reminder' });
  await expect(reminder).toBeVisible();
  const match = page.getByRole('form', { name: 'Court 1 result' });
  const home = match.getByRole('spinbutton').first();
  const away = match.getByRole('spinbutton').last();
  await home.fill('100');
  await away.fill('0');
  await page.getByRole('button', { name: 'Dismiss backup reminder' }).click();
  await expect(reminder).toHaveCount(0);
  await expect(home).toHaveValue('100');
  await match.getByRole('button', { name: 'Save result' }).click();
  expect(await home.evaluate((input: HTMLInputElement) => input.validity.rangeOverflow)).toBe(true);
  await expect(match.getByText('Awaiting result')).toBeVisible();
  await home.fill('99');
  await away.fill('100');
  await match.getByRole('button', { name: 'Save result' }).click();
  expect(await away.evaluate((input: HTMLInputElement) => input.validity.rangeOverflow)).toBe(true);
  await expect(match.getByText('Awaiting result')).toBeVisible();
  for (let save = 1; save <= 5; save++) {
    await away.fill(String(save));
    await match.getByRole('button', { name: 'Save result' }).click();
    await expect(match.getByText(`Saved: 99 – ${save}`, { exact: true })).toBeVisible();
    await expect(reminder).toHaveCount(save === 5 ? 1 : 0);
  }
  const downloadPromise = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Export backup' }).click();
  await downloadPromise;
  await expect(reminder).toHaveCount(0);
  await away.fill('6');
  await match.getByRole('button', { name: 'Save result' }).click();
  await expect(reminder).toHaveCount(0);
});

test('explore the sample and then start a real tournament', async ({ page }) => {
  await page.goto('/');
  await page.getByRole('button', { name: 'Load sample tournament' }).click();
  await expect(page.getByText('8 teams · 2 courts · 8 / 28 matches recorded', { exact: true })).toBeVisible();
  await expect(page.getByRole('heading', { name: 'Round 5 of 14', exact: true })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Load sample tournament' })).toHaveCount(0);
  const rows = page.locator('tbody tr');
  await expect(rows).toHaveCount(8);
  const wins = await rows.evaluateAll(elements => elements.reduce((sum, row) => sum + Number(row.children[2].textContent), 0));
  expect(wins).toBe(8);
  const standings = await rows.allTextContents();
  await page.reload();
  await expect(rows).toHaveText(standings);
  await expect(page.getByRole('heading', { name: 'Round 5 of 14', exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Previous round' }).click();
  await expect(page.getByRole('form', { name: 'Court 1 result' }).getByRole('spinbutton').first()).toHaveValue('11');
  await page.emulateMedia({ media: 'print' });
  await expect(page.locator('.scorecard')).toHaveCount(28);
  await expect(page.locator('.scorecard').first()).toBeVisible();
  await expect(page.getByRole('table')).toBeVisible();
  await page.emulateMedia({ media: 'screen' });
  page.once('dialog', dialog => dialog.accept());
  await page.getByRole('button', { name: 'New tournament' }).click();
  await page.reload();
  await expect(page.getByLabel('Team names')).toHaveValue('');
  await page.getByLabel('Team names').fill('Aces\nSpinners\nLobsters\nDinkers');
  await page.getByRole('button', { name: 'Create tournament' }).click();
  await expect(page.getByText('4 teams · 1 court · 0 / 6 matches recorded', { exact: true })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Load sample tournament' })).toHaveCount(0);
});

test('run, persist, print, and restore a small tournament', async ({ page }) => {
  await page.goto('/');
  await page.getByLabel('Team names').fill('Aces\nSpinners\nLobsters\nDinkers');
  await page.getByLabel('Number of courts').fill('1');
  await page.getByRole('button', { name: 'Create tournament' }).click();
  await expect(page.getByRole('heading', { name: 'Your tournament' })).toBeVisible();
  const match = page.getByRole('form', { name: 'Court 1 result' });
  await match.getByRole('spinbutton', { name: 'Aces home score' }).fill('11');
  await match.getByRole('spinbutton', { name: 'Dinkers away score' }).fill('7');
  await match.getByRole('button', { name: 'Save result' }).click();
  const aces = page.getByRole('row').filter({ has: page.getByRole('rowheader', { name: 'Aces', exact: true }) });
  const dinkers = page.getByRole('row').filter({ has: page.getByRole('rowheader', { name: 'Dinkers', exact: true }) });
  await expect(aces.getByRole('cell')).toHaveText(['1', '1', '11', '7', '+4']);
  await expect(dinkers.getByRole('cell')).toHaveText(['4', '0', '7', '11', '-4']);
  await page.reload();
  await expect(page.getByRole('heading', { name: 'Your tournament' })).toBeVisible();
  await expect(aces.getByRole('cell')).toHaveText(['1', '1', '11', '7', '+4']);
  await page.getByRole('button', { name: 'Previous round' }).click();
  await expect(match.getByRole('spinbutton', { name: 'Aces home score' })).toHaveValue('11');
  // Editing replaces the recorded result rather than counting it twice.
  await match.getByRole('spinbutton', { name: 'Dinkers away score' }).fill('5');
  await match.getByRole('button', { name: 'Save result' }).click();
  await expect(aces.getByRole('cell')).toHaveText(['1', '1', '11', '5', '+6']);
  await match.getByRole('spinbutton', { name: 'Dinkers away score' }).fill('11');
  await match.getByRole('button', { name: 'Save result' }).click();
  await expect(page.getByRole('alert')).toContainText('winner');
  await expect(aces.getByRole('cell')).toHaveText(['1', '1', '11', '5', '+6']);
  await page.emulateMedia({ media: 'print' });
  await expect(page.locator('.scorecard')).toHaveCount(6);
  await expect(page.locator('.scorecard').first()).toBeVisible();
  await expect(page.getByRole('button', { name: 'New tournament' })).toBeHidden();
  await expect(page.getByRole('table')).toBeVisible();
  await page.emulateMedia({ media: 'screen' });
  const downloadPromise = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Export backup' }).click();
  const download = await downloadPromise;
  const backupPath = await download.path();
  page.once('dialog', dialog => dialog.dismiss());
  await page.getByRole('button', { name: 'New tournament' }).click();
  await expect(page.getByRole('heading', { name: 'Your tournament' })).toBeVisible();
  page.once('dialog', dialog => dialog.accept());
  await page.getByRole('button', { name: 'New tournament' }).click();
  await page.reload();
  await expect(page.getByLabel('Team names')).toBeVisible();
  await page.locator('#backup').setInputFiles(backupPath!);
  await expect(aces.getByRole('cell')).toHaveText(['1', '1', '11', '5', '+6']);
  await page.locator('#backup').setInputFiles({ name: 'broken.json', mimeType: 'application/json', buffer: Buffer.from('{}') });
  await expect(page.getByRole('alert')).toContainText('Invalid tournament backup');
  await expect(aces.getByRole('cell')).toHaveText(['1', '1', '11', '5', '+6']);
});
