import { test, expect } from '@playwright/test';

test('run, persist, print, and restore a small tournament', async ({ page }) => {
  await page.goto('/');
  await page.getByLabel('Team names').fill('Aces\nSpinners\nLobsters\nDinkers');
  await page.getByLabel('Number of courts').fill('1');
  await page.getByRole('button', { name: 'Create tournament' }).click();
  await expect(page.getByRole('heading', { name: 'Your tournament' })).toBeVisible();
  const match = page.getByRole('form', { name: 'Court 1 result' });
  await match.getByRole('spinbutton', { name: 'Aces home score' }).fill('11');
  await match.getByRole('spinbutton', { name: 'Dinkers away score' }).fill('7');
  await match.getByRole('button', { name: 'Save result' }).click();
  const aces = page.getByRole('row').filter({ has: page.getByRole('rowheader', { name: 'Aces', exact: true }) });
  const dinkers = page.getByRole('row').filter({ has: page.getByRole('rowheader', { name: 'Dinkers', exact: true }) });
  await expect(aces.getByRole('cell')).toHaveText(['1', '1', '11', '7', '+4']);
  await expect(dinkers.getByRole('cell')).toHaveText(['4', '0', '7', '11', '-4']);
  await page.reload();
  await expect(page.getByRole('heading', { name: 'Your tournament' })).toBeVisible();
  await expect(aces.getByRole('cell')).toHaveText(['1', '1', '11', '7', '+4']);
  await page.getByRole('button', { name: 'Previous round' }).click();
  await expect(match.getByRole('spinbutton', { name: 'Aces home score' })).toHaveValue('11');
  // Editing replaces the recorded result rather than counting it twice.
  await match.getByRole('spinbutton', { name: 'Dinkers away score' }).fill('5');
  await match.getByRole('button', { name: 'Save result' }).click();
  await expect(aces.getByRole('cell')).toHaveText(['1', '1', '11', '5', '+6']);
  await match.getByRole('spinbutton', { name: 'Dinkers away score' }).fill('11');
  await match.getByRole('button', { name: 'Save result' }).click();
  await expect(page.getByRole('alert')).toContainText('winner');
  await expect(aces.getByRole('cell')).toHaveText(['1', '1', '11', '5', '+6']);
  await page.emulateMedia({ media: 'print' });
  await expect(page.locator('.scorecard')).toHaveCount(6);
  await expect(page.locator('.scorecard').first()).toBeVisible();
  await expect(page.getByRole('button', { name: 'New tournament' })).toBeHidden();
  await expect(page.getByRole('table')).toBeVisible();
  await page.emulateMedia({ media: 'screen' });
  const downloadPromise = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Export backup' }).click();
  const download = await downloadPromise;
  const backupPath = await download.path();
  page.once('dialog', dialog => dialog.dismiss());
  await page.getByRole('button', { name: 'New tournament' }).click();
  await expect(page.getByRole('heading', { name: 'Your tournament' })).toBeVisible();
  page.once('dialog', dialog => dialog.accept());
  await page.getByRole('button', { name: 'New tournament' }).click();
  await page.reload();
  await expect(page.getByLabel('Team names')).toBeVisible();
  await page.locator('#backup').setInputFiles(backupPath!);
  await expect(aces.getByRole('cell')).toHaveText(['1', '1', '11', '5', '+6']);
  await page.locator('#backup').setInputFiles({ name: 'broken.json', mimeType: 'application/json', buffer: Buffer.from('{}') });
  await expect(page.getByRole('alert')).toContainText('Invalid tournament backup');
  await expect(aces.getByRole('cell')).toHaveText(['1', '1', '11', '5', '+6']);
});
